version: '3'

services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    container_name: jenkins-lts
    restart: on-failure
    networks:
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

networks:
  jenkins:

volumes:
  jenkins-data:
  jenkins-docker-certs:
